export const improvementsArray = [
  {
    title: 'Спорт',
    img: '/uploads/improvements/01.png',
    type: 'Тело',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Питание',
    img: '/uploads/improvements/02.png',
    type: 'Тело',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Сон',
    img: '/uploads/improvements/03.png',
    type: 'Тело',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Мозг',
    img: '/uploads/improvements/04.png',
    type: 'Тело',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Дисциплина',
    img: '/uploads/improvements/05.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Инициативность',
    img: '/uploads/improvements/06.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Стрессо-устойчивость',
    img: '/uploads/improvements/07.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Креативность',
    img: '/uploads/improvements/08.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Этика',
    img: '/uploads/improvements/09.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Само-уверенность',
    img: '/uploads/improvements/10.png',
    type: 'Персональные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Эмоциональный интеллект',
    img: '/uploads/improvements/11.png',
    type: 'Когнитивные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Критическое мышление',
    img: '/uploads/improvements/12.png',
    type: 'Когнитивные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Внимание',
    img: '/uploads/improvements/13.png',
    type: 'Когнитивные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Память',
    img: '/uploads/improvements/14.png',
    type: 'Когнитивные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Логика',
    img: '/uploads/improvements/15.png',
    type: 'Когнитивные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Умение убеждать ',
    img: '/uploads/improvements/16.png',
    type: 'Коммуникативные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Ведение переговоров',
    img: '/uploads/improvements/17.png',
    type: 'Коммуникативные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Эмпатия',
    img: '/uploads/improvements/18.png',
    type: 'Коммуникативные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Управление конфликтами',
    img: '/uploads/improvements/19.png',
    type: 'Коммуникативные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Публичные выступления',
    img: '/uploads/improvements/20.png',
    type: 'Коммуникативные навыки',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Лидерство',
    img: '/uploads/improvements/21.png',
    type: 'Навыки управления',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Управление проектами',
    img: '/uploads/improvements/22.png',
    type: 'Навыки управления',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Планирование',
    img: '/uploads/improvements/23.png',
    type: 'Навыки управления',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
  {
    title: 'Мотивация команды',
    img: '/uploads/improvements/24.png',
    type: 'Навыки управления',
    cost: 3000,
    profit: 350,
    required_level: 0,
  },
];
